import { createLogger, type MemoryContext } from "@opsmind/shared";
import { getAgentConfig, getEnv } from "@opsmind/config";
import { DecisionRepository } from "../repositories/decision.repository";
import { OperationalStateRepository } from "../repositories/state.repository";
import { ActionRepository } from "../repositories/action.repository";
import { VectorStore } from "../vector-memory/vector-store";
import { type DecisionDocument } from "../collections/decisions/schema";
import { type ActionDocument } from "../collections/actions/schema";

// Sub-document types inferred from collection schemas
type DecisionFinding = DecisionDocument["findings"][number];
type OperationalStateAnomaly = NonNullable<import("../collections/state/schema").OperationalStateDocument["anomalies"]>[number];
type OperationalStateMetric = NonNullable<import("../collections/state/schema").OperationalStateDocument["metrics"]>[number];

const logger = createLogger("ContextAssembler");

/**
 * Context Assembler — builds the memory context injected into each reasoning step.
 *
 * Retrieval strategy (in priority order):
 * 1. Vector Search (semantic similarity) — when VECTOR_SEARCH_ENABLED=true and
 *    a queryEmbedding is provided. Finds the most semantically similar past decisions,
 *    not just the most recent ones.
 * 2. Category + recency fallback — when vector search is disabled or no embedding
 *    is provided. Retrieves recent decisions filtered by category.
 *
 * This is what makes OpsMind improve over time — each session has access to
 * the accumulated intelligence from all previous sessions, retrieved by relevance.
 */

export interface AssembledContext {
  memoryContext: MemoryContext;
  currentStateSnapshot: string;
  historicalDecisionSummaries: HistoricalDecisionSummary[];
  relevantAnomalyHistory: AnomalyHistoryEntry[];
  successfulActionPatterns: ActionPatternSummary[];
  /** True if decisions were retrieved via semantic similarity (Vector Search) */
  usedVectorSearch: boolean;
}

export interface HistoricalDecisionSummary {
  id: string;
  goal: string;
  category: string;
  summary: string;
  confidenceScore: number;
  keyFindings: string[];
  createdAt: Date;
  /** Similarity score when retrieved via Vector Search (0–1) */
  similarityScore?: number;
}

export interface AnomalyHistoryEntry {
  metric: string;
  description: string;
  severity: string;
  resolvedAt?: Date;
  relatedDecisionId?: string;
}

export interface ActionPatternSummary {
  title: string;
  description: string;
  wasSuccessful: boolean;
  estimatedImpact: string;
}

export class ContextAssembler {
  private readonly decisionRepo = new DecisionRepository();
  private readonly stateRepo = new OperationalStateRepository();
  private readonly actionRepo = new ActionRepository();
  private readonly vectorStore = new VectorStore();

  /**
   * Assembles the full memory context for a reasoning session.
   *
   * @param goal - The current agent goal
   * @param category - The goal category (used for category-specific fallback retrieval)
   * @param queryEmbedding - Optional embedding of the goal for semantic retrieval.
   *   Generated by packages/ai and passed here to avoid a cross-package dependency.
   *   When provided and VECTOR_SEARCH_ENABLED=true, uses Atlas Vector Search.
   */
  async assembleContext(
    goal: string,
    category: string,
    queryEmbedding?: number[] | null
  ): Promise<AssembledContext> {
    const config = getAgentConfig();
    const env = getEnv();
    const limit = config.memoryRetrievalLimit;

    logger.info("Assembling memory context", {
      goal: goal.slice(0, 100),
      category,
      vectorSearchEnabled: env.VECTOR_SEARCH_ENABLED,
      hasEmbedding: queryEmbedding != null && queryEmbedding.length > 0,
    });

    // ── Decision retrieval — semantic or temporal ────────────────────────────
    let allDecisions: DecisionDocument[];
    let usedVectorSearch = false;

    const useVector =
      env.VECTOR_SEARCH_ENABLED &&
      queryEmbedding != null &&
      queryEmbedding.length > 0;

    if (useVector) {
      // Semantic retrieval via Atlas Vector Search
      const similarDecisions = await this.vectorStore.findSimilarDecisions(
        queryEmbedding!,
        limit
      );
      allDecisions = similarDecisions.map((r) => r.decision);
      usedVectorSearch = similarDecisions.length > 0;

      logger.info("Vector search retrieval", {
        retrieved: similarDecisions.length,
        topScore: similarDecisions[0]?.similarityScore?.toFixed(3) ?? "n/a",
      });
    } else {
      // Temporal fallback — recent + category-specific, deduplicated
      const [recentDecisions, categoryDecisions] = await Promise.all([
        this.decisionRepo.findRecentFinalized(limit).catch((err) => {
          logger.warn("Failed to fetch recent decisions", { error: String(err) });
          return [] as import("../collections/decisions/schema").DecisionDocument[];
        }),
        this.decisionRepo.findByCategory(
          category as Parameters<DecisionRepository["findByCategory"]>[0],
          limit
        ).catch((err) => {
          logger.warn("Failed to fetch category decisions", { error: String(err) });
          return [] as import("../collections/decisions/schema").DecisionDocument[];
        }),
      ]);

      const seenIds = new Set<string>();
      allDecisions = [...recentDecisions, ...categoryDecisions].filter((d) => {
        if (seenIds.has(d._id)) return false;
        seenIds.add(d._id);
        return true;
      });
    }

    // ── Parallel fetch of remaining context ──────────────────────────────────
    // Each fetch is wrapped individually — failures return empty arrays rather
    // than crashing the pipeline. Context enrichment is best-effort.
    const [currentState, pendingActions, successfulActions] = await Promise.all([
      this.stateRepo.findCurrent().catch((err) => {
        logger.warn("Failed to fetch current state — using empty context", { error: String(err) });
        return null;
      }),
      this.actionRepo.findPending().catch((err) => {
        logger.warn("Failed to fetch pending actions — skipping", { error: String(err) });
        return [] as import("../collections/actions/schema").ActionDocument[];
      }),
      this.actionRepo.findCompletedWithOutcomes(limit).catch((err) => {
        logger.warn("Failed to fetch completed actions — skipping", { error: String(err) });
        return [] as import("../collections/actions/schema").ActionDocument[];
      }),
    ]);

    // ── Build historical decision summaries ───────────────────────────────────
    const historicalDecisionSummaries: HistoricalDecisionSummary[] = allDecisions.map(
      (d: DecisionDocument): HistoricalDecisionSummary => ({
        id: d._id,
        goal: d.goal,
        category: d.category,
        summary: d.summary,
        confidenceScore: d.confidenceScore,
        keyFindings: d.findings.slice(0, 3).map((f: DecisionFinding) => f.title),
        createdAt: d.createdAt,
      })
    );

    // ── Build anomaly history ─────────────────────────────────────────────────
    const relevantAnomalyHistory: AnomalyHistoryEntry[] =
      currentState?.anomalies.map(
        (a: OperationalStateAnomaly): AnomalyHistoryEntry => ({
          metric: a.metric,
          description: a.description,
          severity: a.severity,
          resolvedAt: a.resolvedAt,
          relatedDecisionId: a.relatedDecisionId,
        })
      ) ?? [];

    // ── Build action pattern summaries ────────────────────────────────────────
    type ActionWithOutcome = ActionDocument & {
      outcome: NonNullable<ActionDocument["outcome"]>;
    };
    const actionsWithOutcome = successfulActions.filter(
      (a: ActionDocument): a is ActionWithOutcome => a.outcome !== undefined
    );

    const successfulActionPatterns: ActionPatternSummary[] = actionsWithOutcome.map(
      (a: ActionWithOutcome): ActionPatternSummary => ({
        title: a.title,
        description: a.description,
        wasSuccessful: a.outcome.wasSuccessful,
        estimatedImpact: a.estimatedImpact,
      })
    );

    // ── Build MemoryContext for prompt injection ───────────────────────────────
    const memoryContext: MemoryContext = {
      relevantDecisions: historicalDecisionSummaries.map(
        (d: HistoricalDecisionSummary) =>
          `[${d.category}] ${d.goal}: ${d.summary} (confidence: ${d.confidenceScore.toFixed(2)})`
      ),
      historicalPatterns: successfulActionPatterns
        .filter((p: ActionPatternSummary) => p.wasSuccessful)
        .map(
          (p: ActionPatternSummary) =>
            `${p.title}: ${p.description} (impact: ${p.estimatedImpact})`
        ),
      previousOutcomes: actionsWithOutcome.map(
        (a: ActionWithOutcome) =>
          `${a.title}: ${a.outcome.wasSuccessful ? "SUCCESS" : "FAILED"} — ${a.outcome.notes}`
      ),
      operationalState: currentState
        ? {
            summary: currentState.summary,
            anomalyCount: currentState.anomalies.length,
            activeInvestigations: currentState.activeInvestigations.length,
            metrics: currentState.metrics
              .slice(0, 10)
              .map((m: OperationalStateMetric) => ({
                name: m.name,
                value: m.value,
                unit: m.unit,
                trend: m.trend,
                isAnomaly: m.isAnomaly,
              })),
          }
        : {},
    };

    logger.info("Memory context assembled", {
      historicalDecisions: historicalDecisionSummaries.length,
      anomalies: relevantAnomalyHistory.length,
      actionPatterns: successfulActionPatterns.length,
      pendingActions: pendingActions.length,
      usedVectorSearch,
    });

    return {
      memoryContext,
      currentStateSnapshot: currentState?.summary ?? "No operational state available",
      historicalDecisionSummaries,
      relevantAnomalyHistory,
      successfulActionPatterns,
      usedVectorSearch,
    };
  }

  /**
   * Assembles a lightweight context for quick lookups.
   */
  async assembleMinimalContext(): Promise<MemoryContext> {
    const config = getAgentConfig();

    const [currentState, recentDecisions] = await Promise.all([
      this.stateRepo.findCurrent(),
      this.decisionRepo.findRecentFinalized(Math.min(config.memoryRetrievalLimit, 3)),
    ]);

    return {
      relevantDecisions: recentDecisions.map(
        (d: DecisionDocument) => `${d.goal}: ${d.summary}`
      ),
      historicalPatterns: [],
      previousOutcomes: [],
      operationalState: currentState ? { summary: currentState.summary } : {},
    };
  }
}
