import { createLogger, generateLogId } from "@opsmind/shared";
import { type Decision, type ActionRecommendation } from "@opsmind/shared";
import { DecisionRepository } from "../repositories/decision.repository";
import { ActionRepository } from "../repositories/action.repository";
import { ExecutionLogRepository } from "../repositories/log.repository";
import { SessionRepository } from "../repositories/session.repository";
import { type DecisionDocument } from "../collections/decisions/schema";
import { type ActionDocument } from "../collections/actions/schema";
import { type InsertExecutionLogDocument } from "../collections/logs/schema";

const logger = createLogger("MemoryWriter");

/**
 * Memory Writer — persists agent reasoning outputs to MongoDB.
 *
 * This is the final step of every reasoning pipeline execution.
 * Every decision, action, and log entry flows through this writer.
 *
 * Rule: every important reasoning step MUST be persisted (ENGINEERING_RULES §2.2).
 */
export class MemoryWriter {
  private readonly decisionRepo = new DecisionRepository();
  private readonly actionRepo = new ActionRepository();
  private readonly logRepo = new ExecutionLogRepository();
  private readonly sessionRepo = new SessionRepository();

  /**
   * Persists a finalized decision and all its action recommendations.
   * Called at the end of the memory_persistence pipeline step.
   *
   * @param decision - The finalized decision to persist
   * @param embedding - Optional embedding vector for Atlas Vector Search.
   *   Generated by packages/ai and passed here to avoid a cross-package dependency.
   *   If null/undefined, the decision is persisted without an embedding and
   *   falls back to recency-based retrieval.
   */
  async persistDecision(decision: Decision, embedding?: number[] | null): Promise<void> {
    logger.info("Persisting decision to memory", {
      decisionId: decision.id,
      sessionId: decision.sessionId,
      category: decision.category,
      hasEmbedding: embedding != null && embedding.length > 0,
    });

    const document: DecisionDocument = {
      _id: decision.id,
      sessionId: decision.sessionId,
      goal: decision.goal,
      category: decision.category,
      status: decision.status,
      summary: decision.summary,
      reasoning: decision.reasoning,
      findings: decision.findings,
      recommendations: decision.recommendations,
      reflection: decision.reflection,
      confidenceScore: decision.confidenceScore,
      confidenceLevel: decision.confidenceLevel,
      reasoningTrace: decision.reasoningTrace,
      toolsUsed: decision.toolsUsed,
      memoryReferences: decision.memoryReferences,
      // Include embedding if provided — enables Atlas Vector Search
      ...(embedding != null && embedding.length > 0 ? { embedding } : {}),
      createdAt: decision.createdAt,
      updatedAt: decision.updatedAt,
    };

    await this.decisionRepo.insertOne(document);

    if (decision.recommendations.length > 0) {
      await this.persistActions(decision.recommendations, decision.id, decision.sessionId);
    }

    logger.info("Decision persisted successfully", {
      decisionId: decision.id,
      embeddingStored: embedding != null && embedding.length > 0,
    });
  }

  /**
   * Persists action recommendations as individual trackable documents.
   * Actions are stored separately so their status can be tracked independently.
   */
  async persistActions(
    recommendations: ActionRecommendation[],
    decisionId: string,
    sessionId: string
  ): Promise<void> {
    const now = new Date();

    const documents: ActionDocument[] = recommendations.map((rec) => ({
      _id: rec.id,
      decisionId,
      sessionId,
      title: rec.title,
      description: rec.description,
      rationale: rec.rationale,
      priority: rec.priority,
      status: rec.status,
      estimatedImpact: rec.estimatedImpact,
      timeframe: rec.timeframe,
      risks: rec.risks,
      statusHistory: [
        {
          from: "none",
          to: rec.status,
          changedAt: now,
        },
      ],
      createdAt: now,
      updatedAt: now,
    }));

    await Promise.all(documents.map((doc) => this.actionRepo.insertOne(doc)));
  }

  /**
   * Writes a structured execution log entry.
   * Called throughout the reasoning pipeline for full traceability.
   */
  async writeLog(
    entry: Omit<InsertExecutionLogDocument, "_id" | "timestamp">
  ): Promise<void> {
    const document: InsertExecutionLogDocument = {
      _id: generateLogId(),
      timestamp: new Date(),
      ...entry,
    };

    await this.logRepo.appendLog(document);
  }

  /**
   * Stores an embedding vector for an existing decision.
   * Called asynchronously after persistDecision() — non-blocking.
   */
  async storeEmbedding(decisionId: string, embedding: number[]): Promise<void> {
    await this.decisionRepo.saveEmbedding(decisionId, embedding);
    logger.debug("Embedding stored for decision", { decisionId, dimensions: embedding.length });
  }

  /**
   * Attaches the reflection output to an existing decision and finalizes it.
   * Called after the reflection_loop pipeline step completes.
   */
  async attachReflection(
    decisionId: string,
    reflection: Decision["reflection"],
    finalConfidenceScore: number
  ): Promise<void> {
    if (!reflection) return;

    logger.info("Attaching reflection to decision", { decisionId });

    await this.decisionRepo.updateDecision(decisionId, {
      reflection,
      confidenceScore: finalConfidenceScore,
      status: "finalized",
      updatedAt: new Date(),
    });
  }

  /**
   * Marks a session as completed and links it to its decision.
   */
  async finalizeSession(
    sessionId: string,
    decisionId: string,
    durationMs: number
  ): Promise<void> {
    await this.sessionRepo.markCompleted(sessionId, decisionId, durationMs);
  }

  /**
   * Records a session failure with full error context.
   */
  async recordSessionFailure(
    sessionId: string,
    error: { code: string; message: string; step?: string }
  ): Promise<void> {
    await this.sessionRepo.markFailed(sessionId, error);
  }
}
